### ISSUE TITLE
Misleading comment in example nft.conf scripts

### ISSUE THREAD

**Issue by mycomm** [wirefalls/geo-nft#12]
In the example IPv4 nft.conf file....

The "table netdev filter" uses the set @geo-netdev4
and the rule explictly drops packets in that set.
 ip saddr @geo-netdev4 counter drop comment "Drop source addresses in set geo-netdev4"

In the next section, the "table inet filter" creates the set @geo-inet4 and the comment infers the same type of filter behavior.

  # We can do geolocation packet filtering in this table too.
  # Define empty set to store IPv4 country code specific address ranges.
  set geo-inet4 {
    type ipv4_addr
    flags interval
    # Elements for this set are defined in /etc/nftables/geo-nft/refill-sets.conf
  }

But there is no saddr filtering on the set @geo-inet4.

The @geo-inet4 set is used later for daddr filtering.

I don't know if the intent was to do saddr filtering in the "table inet filter" or not, but the comment should be a little clearer if you are only going to use it for daddr.

The same logic looks like it is in the IP4, IP6 and combined examples.

**Comment by wirefalls** [comment]
Thank you for your input.

The geolocation packet filtering comment is intended to covey that geolocation packet filtering can take place in other tables besides the netdev filter table. The term "geolocation packet filtering" doesn't specify or imply whether source or destination address matching is being done, so I don't see where that specific term is misleading.  

***But there is no saddr filtering on the set @geo-inet4.***  

***The @geo-inet4 set is used later for daddr filtering.***  

***I don't know if the intent was to do saddr filtering in the "table inet filter" or not, but the comment should be a little clearer if you are only going to use it for daddr.***

For the specific example shown, there wasn't any intent to do geolocation source address filtering in the inet filter table because geolocation source address filtering is already being done upstream in the netdev filter table. The firewall examples intentionally use destination address filtering in the (inet, ip, or ip6) filter table rules to demonstrate that outgoing traffic can be filtered as well. The outgoing firewall rule examples state in the preceding comments that they apply to outgoing traffic to destination address ranges. The nftables set @geo-inet4 used in the example can be used for either source or destination address filtering, depending on which is specified by the individual firewall rule.

Please let me know if I'm misunderstanding the issue. Updating the documentation is not a problem, but I'd like to understand the justification before doing so.

Thank you

**Comment by wirefalls** [comment]
I'm going to close this issue, feel free to reopen it if needed. The Discussions link at the top of the page is available if you have additional questions.

Thanks
